### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by jornane** [sjm-steffann/nat64check#1]
I wasn't able to install this on a stock Debian 8 machine. Could you add an installation guide with operating system and Python requirements?

I cannot get scikit-image to work properly:

```
Downloading/unpacking scikit-image
  Downloading scikit-image-0.12.3.tar.gz (20.7MB): 20.7MB downloaded
  Running setup.py (path:/tmp/pip-build-4_6rl3b3/scikit-image/setup.py) egg_info for package scikit-image
    No eggs found in /tmp/easy_install-qs6pglxj/Cython-0.25.2/egg-dist-tmp-uug3df7h (setup script problem?)
    Unable to find pgen, not compiling formal grammar.
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-4_6rl3b3/scikit-image/setup.py", line 146, in <module>
        **extra
      File "/opt/venv/nat64check/lib/python3.4/site-packages/numpy/distutils/core.py", line 126, in setup
        dist = setup(**new_attr)
      File "/opt/venv/nat64check/lib/python3.4/site-packages/numpy/distutils/core.py", line 169, in setup
        return old_setup(**new_attr)
      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/opt/venv/nat64check/lib/python3.4/site-packages/numpy/distutils/numpy_distribution.py", line 16, in __init__
        Distribution.__init__(self, attrs)
      File "/opt/venv/nat64check/lib/python3.4/site-packages/setuptools/dist.py", line 262, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/opt/venv/nat64check/lib/python3.4/site-packages/setuptools/dist.py", line 287, in fetch_build_eggs
        replace_conflicting=True,
      File "/opt/venv/nat64check/lib/python3.4/site-packages/pkg_resources.py", line 639, in resolve
        raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: cython>=0.21
    Complete output from command python setup.py egg_info:
    No eggs found in /tmp/easy_install-qs6pglxj/Cython-0.25.2/egg-dist-tmp-uug3df7h (setup script problem?)

Unable to find pgen, not compiling formal grammar.

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-4_6rl3b3/scikit-image/setup.py", line 146, in <module>

    **extra

  File "/opt/venv/nat64check/lib/python3.4/site-packages/numpy/distutils/core.py", line 126, in setup

    dist = setup(**new_attr)

  File "/opt/venv/nat64check/lib/python3.4/site-packages/numpy/distutils/core.py", line 169, in setup

    return old_setup(**new_attr)

  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup

    _setup_distribution = dist = klass(attrs)

  File "/opt/venv/nat64check/lib/python3.4/site-packages/numpy/distutils/numpy_distribution.py", line 16, in __init__

    Distribution.__init__(self, attrs)

  File "/opt/venv/nat64check/lib/python3.4/site-packages/setuptools/dist.py", line 262, in __init__

    self.fetch_build_eggs(attrs['setup_requires'])

  File "/opt/venv/nat64check/lib/python3.4/site-packages/setuptools/dist.py", line 287, in fetch_build_eggs

    replace_conflicting=True,

  File "/opt/venv/nat64check/lib/python3.4/site-packages/pkg_resources.py", line 639, in resolve

    raise DistributionNotFound(req)

pkg_resources.DistributionNotFound: cython>=0.21
```

**Comment by steffann** [comment]
NAT64Check is quite complex to set up. You need a cluster of servers with different connectivity options (v4, v6, NAT64) etc to run phantomJS on. Plus off course a dual stack controller for the web interface and the scheduling. Writing an installation manual will be complex, but I'll help you install it if I can.

**Comment by jornane** [comment]
We've decided not to implement a NAT64 check service at this time, since it would take too much time to do so.
